// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Shared.Net
{
    public sealed class PlaceBlocksGameEventFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Shared.Net.PlaceBlocksGameEvent>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Shared.Net.PlaceBlocksGameEvent value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(6);
            writer.Write(value.Id);
            writer.Write(value.CharacterShortId);
            writer.Write(value.X);
            writer.Write(value.Y);
            writer.Write(value.Z);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Shared.BlockId>(formatterResolver).Serialize(ref writer, value.Block, options);
        }

        public global::Shared.Net.PlaceBlocksGameEvent Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __Id__ = default(int);
            var __CharacterShortId__ = default(ushort);
            var __X__ = default(short);
            var __Y__ = default(short);
            var __Z__ = default(short);
            var __Block__ = default(global::Shared.BlockId);

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        __Id__ = reader.ReadInt32();
                        break;
                    case 1:
                        __CharacterShortId__ = reader.ReadUInt16();
                        break;
                    case 2:
                        __X__ = reader.ReadInt16();
                        break;
                    case 3:
                        __Y__ = reader.ReadInt16();
                        break;
                    case 4:
                        __Z__ = reader.ReadInt16();
                        break;
                    case 5:
                        __Block__ = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Shared.BlockId>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Shared.Net.PlaceBlocksGameEvent(__Id__, __CharacterShortId__, __X__, __Y__, __Z__, __Block__);
            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
