// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.VoxelsEngine.Data
{
    public sealed class MainTextureJsonFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::VoxelsEngine.Data.MainTextureJson>
    {
        // MainAlbedoTexture
        private static global::System.ReadOnlySpan<byte> GetSpan_MainAlbedoTexture() => new byte[1 + 17] { 177, 77, 97, 105, 110, 65, 108, 98, 101, 100, 111, 84, 101, 120, 116, 117, 114, 101 };
        // MainNormalsTexture
        private static global::System.ReadOnlySpan<byte> GetSpan_MainNormalsTexture() => new byte[1 + 18] { 178, 77, 97, 105, 110, 78, 111, 114, 109, 97, 108, 115, 84, 101, 120, 116, 117, 114, 101 };
        // MainHeightsTexture
        private static global::System.ReadOnlySpan<byte> GetSpan_MainHeightsTexture() => new byte[1 + 18] { 178, 77, 97, 105, 110, 72, 101, 105, 103, 104, 116, 115, 84, 101, 120, 116, 117, 114, 101 };

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::VoxelsEngine.Data.MainTextureJson value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value is null)
            {
                writer.WriteNil();
                return;
            }

            var formatterResolver = options.Resolver;
            writer.WriteMapHeader(3);
            writer.WriteRaw(GetSpan_MainAlbedoTexture());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.MainAlbedoTexture, options);
            writer.WriteRaw(GetSpan_MainNormalsTexture());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.MainNormalsTexture, options);
            writer.WriteRaw(GetSpan_MainHeightsTexture());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.MainHeightsTexture, options);
        }

        public global::VoxelsEngine.Data.MainTextureJson Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var ____result = new global::VoxelsEngine.Data.MainTextureJson();

            for (int i = 0; i < length; i++)
            {
                var stringKey = global::MessagePack.Internal.CodeGenHelpers.ReadStringSpan(ref reader);
                switch (stringKey.Length)
                {
                    default:
                    FAIL:
                      reader.Skip();
                      continue;
                    case 17:
                        if (!global::System.MemoryExtensions.SequenceEqual(stringKey, GetSpan_MainAlbedoTexture().Slice(1))) { goto FAIL; }

                        ____result.MainAlbedoTexture = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        continue;
                    case 18:
                        switch (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey))
                        {
                            default: goto FAIL;
                            case 7886488280129691981UL:
                                if (!global::System.MemoryExtensions.SequenceEqual(stringKey, GetSpan_MainNormalsTexture().Slice(1 + 8))) { goto FAIL; }

                                ____result.MainNormalsTexture = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                                continue;

                            case 7451598420225646925UL:
                                if (!global::System.MemoryExtensions.SequenceEqual(stringKey, GetSpan_MainHeightsTexture().Slice(1 + 8))) { goto FAIL; }

                                ____result.MainHeightsTexture = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                                continue;

                        }

                }
            }

            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
