// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters
{
    public sealed class BlockSideJsonFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::BlockSideJson>
    {
        // Directions
        private static global::System.ReadOnlySpan<byte> GetSpan_Directions() => new byte[1 + 10] { 170, 68, 105, 114, 101, 99, 116, 105, 111, 110, 115 };
        // MainTextureConfig
        private static global::System.ReadOnlySpan<byte> GetSpan_MainTextureConfig() => new byte[1 + 17] { 177, 77, 97, 105, 110, 84, 101, 120, 116, 117, 114, 101, 67, 111, 110, 102, 105, 103 };
        // FrameTextureConfig
        private static global::System.ReadOnlySpan<byte> GetSpan_FrameTextureConfig() => new byte[1 + 18] { 178, 70, 114, 97, 109, 101, 84, 101, 120, 116, 117, 114, 101, 67, 111, 110, 102, 105, 103 };

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::BlockSideJson value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value is null)
            {
                writer.WriteNil();
                return;
            }

            var formatterResolver = options.Resolver;
            writer.WriteMapHeader(3);
            writer.WriteRaw(GetSpan_Directions());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Shared.DirectionFlag>(formatterResolver).Serialize(ref writer, value.Directions, options);
            writer.WriteRaw(GetSpan_MainTextureConfig());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.MainTextureConfig, options);
            writer.WriteRaw(GetSpan_FrameTextureConfig());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.FrameTextureConfig, options);
        }

        public global::BlockSideJson Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var ____result = new global::BlockSideJson();

            for (int i = 0; i < length; i++)
            {
                var stringKey = global::MessagePack.Internal.CodeGenHelpers.ReadStringSpan(ref reader);
                switch (stringKey.Length)
                {
                    default:
                    FAIL:
                      reader.Skip();
                      continue;
                    case 10:
                        if (!global::System.MemoryExtensions.SequenceEqual(stringKey, GetSpan_Directions().Slice(1))) { goto FAIL; }

                        ____result.Directions = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Shared.DirectionFlag>(formatterResolver).Deserialize(ref reader, options);
                        continue;
                    case 17:
                        if (!global::System.MemoryExtensions.SequenceEqual(stringKey, GetSpan_MainTextureConfig().Slice(1))) { goto FAIL; }

                        ____result.MainTextureConfig = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        continue;
                    case 18:
                        if (!global::System.MemoryExtensions.SequenceEqual(stringKey, GetSpan_FrameTextureConfig().Slice(1))) { goto FAIL; }

                        ____result.FrameTextureConfig = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        continue;

                }
            }

            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
