// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Shared
{
    public sealed class ChunkFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Shared.Chunk>
    {
        // Cells
        private static global::System.ReadOnlySpan<byte> GetSpan_Cells() => new byte[1 + 5] { 165, 67, 101, 108, 108, 115 };
        // IsGenerated
        private static global::System.ReadOnlySpan<byte> GetSpan_IsGenerated() => new byte[1 + 11] { 171, 73, 115, 71, 101, 110, 101, 114, 97, 116, 101, 100 };

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Shared.Chunk value, global::MessagePack.MessagePackSerializerOptions options)
        {
            var formatterResolver = options.Resolver;
            writer.WriteMapHeader(2);
            writer.WriteRaw(GetSpan_Cells());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Shared.Cell[,,]>(formatterResolver).Serialize(ref writer, value.Cells, options);
            writer.WriteRaw(GetSpan_IsGenerated());
            writer.Write(value.IsGenerated);
        }

        public global::Shared.Chunk Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            var formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var ____result = new global::Shared.Chunk();

            for (int i = 0; i < length; i++)
            {
                var stringKey = global::MessagePack.Internal.CodeGenHelpers.ReadStringSpan(ref reader);
                switch (stringKey.Length)
                {
                    default:
                    FAIL:
                      reader.Skip();
                      continue;
                    case 5:
                        if (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey) != 495740282179UL) { goto FAIL; }

                        ____result.Cells = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Shared.Cell[,,]>(formatterResolver).Deserialize(ref reader, options);
                        continue;
                    case 11:
                        if (!global::System.MemoryExtensions.SequenceEqual(stringKey, GetSpan_IsGenerated().Slice(1))) { goto FAIL; }

                        ____result.IsGenerated = reader.ReadBoolean();
                        continue;

                }
            }

            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
